name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v2
      name: Build the Docker image
      run: docker build ./ --no-cache --build-arg GOLANG_VERSION=1.17.2 --build-arg DEFAULTNETWORK=datanet101 --tag fimbaz/algorand-datanet101:${GITHUB_REF##*/}  --tag fimbaz/algorand-datanet101:latest
    - name: push the Docker image
      run: docker push fimbaz/algorand-datanet101:${GITHUB_REF##*/}
    - name: push the Docker image
      run: docker push fimbaz/algorand-datanet101:latest
      
      
